### ISSUE TITLE
Clarify in README.md how to set more than one endpoints class in web.xml

### ISSUE THREAD

**Issue by pauloleitemoreira** [cloudendpoints/endpoints-java#10]
I toke some time to figure out how to set more than one endpoints class in web.xml.

I just suggest to update it from: 

    <init-param>
        <param-name>services</param-name>
        <param-value>com.example.YourEndpoint</param-value>
    </init-param>

to

    <init-param>
        <param-name>services</param-name>
        <param-value>com.example.YourEndpointOne, com.example.YourEndpointTwo</param-value>
    </init-param>

**Comment by tangiel** [comment]
Fixed in #11.
