### ISSUE TITLE
Log entry for request that returns HTTP 400 is at INFO instead of WARN

### ISSUE THREAD

**Issue by william-ferguson-au** [cloudendpoints/endpoints-java#114]
This is really disconcerting. Looking at the logs at first glance it appears like all the requests are fine because they have the little blue "i" (INFO) icon. But closer examination shows that even when the HTTP response was 400 (eg the method threw  a BadRequestException) the request is still logged at INFO.

Could we please get non 200 responses logged at least at warning?

**Comment by tangiel** [comment]
@william-ferguson-au apologies for missing this. Is this an exception thrown from your code or Endpoints? Can you paste an example of the entire log message?

**Comment by william-ferguson-au** [comment]
It's an Exception from the application code, not from the endpoints infrastructure.

`
06:21:42.551
POST
400
245 B
371 ms
Recorder Google-HTTP-Java-Client/1.18.0-rc (gzip)
/_ah/api/licenceTokenConverter/v1/convertLicenceToken
 60.226.102.146 - - [06/Dec/2017:06:21:42 +1000] "POST /_ah/api/licenceTokenConverter/v1/convertLicenceToken HTTP/1.1" 400 245 - "Recorder Google-HTTP-Java-Client/1.18.0-rc (gzip)" "wylas-licence-server.appspot.com" ms=371 cpu_ms=144 cpm_usd=2.738e-8 loading_request=0 instance=00c61b117c77eaabb7563908a7c0efaf91599593ddc30cd61428aaf09096804f51af566502550154 app_engine_release=1.9.54 trace_id=-`

In this case a BadRequest was thrown by the app, but the above was logged at INFO as the first entry for the request. As you can see the request has returned HTTP 400, but it is logged at INFO, so when looking at the logs it is not at all obvious that there was an issue with this request. It seems (and I could be wrong here) that the request log entry is logged at the loudest log level of any log during the processing of that request.

I would have expected that an error crossing the HTTP boundary would be logged at WARN or higher.

**Comment by tangiel** [comment]
I see. Endpoints was changed to log 400 level errors at INFO because 400 level errors typically indicate a user error, not a code error. Is there some reason you're particularly interested in user errors that requires logging at a higher level? Perhaps we can refactor `ServiceException` to allow optional overriding of the log level.

**Comment by william-ferguson-au** [comment]
I'm interested in all instances where the service fails to provide its expected result. Yes 400 == client error, which means that it is a client misusing the API, which is noteworthy. Either there is a bug in the client or (in this case) the client is malicious.

**Comment by william-ferguson-au** [comment]
That would work, thanks.

I presume that other RuntimeExceptions crossing the HTTP boundary  (such as a NullPointer) are logged at ERROR and generate a HTTP 500?

**Comment by tangiel** [comment]
Yes. This helper has been added in #120 and will be going out shortly in version 2.0.10.
