### ISSUE TITLE
Servlet 3.1

### ISSUE THREAD

**Issue by elharo** [cloudendpoints/endpoints-java#126]
Following along with the tutorial at https://cloud.google.com/endpoints/docs/frameworks/java/get-started-frameworks-java I gather that this is expected to be deployed to the App Engine Standard java8 runtime.

This runtime provides version 3.1 of the Java Servlet API. However this project specifies version 2.5 of the servlet API in gradle.properties.

We should probably upgrade unless it's also necessary to support the deprecated java7 runtime. If so, then a more complex fix may be needed.

**Comment by patflynn** [comment]
@tangiel ping.  the servlet API dep would ideally be 'provided' scope in the pom.xml.

**Comment by patflynn** [comment]
this is a high priority bug as any java 8 users on 3.1 api will be blocked from using this dep.

**Comment by tangiel** [comment]
#129
