### ISSUE TITLE
2.0.14

### ISSUE THREAD

**Issue by elharo** [cloudendpoints/endpoints-java#144]
2.0.14 is on Maven central but only 2.0.13 here. Does something need to be updated? Is this the canonical repo for these artifacts?

**Comment by tangiel** [comment]
Forgot to push.

**Comment by elharo** [comment]
https://github.com/cloudendpoints/endpoints-java/releases still needs to be updated. How did something get onto Maven Central without being pushed here first?

**Comment by tangiel** [comment]
The release process isn't done through CI or anything. I forgot to push.
