### ISSUE TITLE
Long/long types are changed to String in JavaClients

### ISSUE THREAD

**Issue by Burtan** [cloudendpoints/endpoints-java#38]
Hi,
I'm referring to this issue: https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin/issues/17

**Comment by Burtan** [comment]
Does the JavaClient generation use the discovery doc? I've just checked the v1 doc and you are right, it's the same as with v2. Still the JavaClient uses String instead of Long in v2

**Comment by tangiel** [comment]
Yes, it uses the discovery doc. Looks like there is a mistake, will be fixed by #39. Thanks for the report!

**Comment by Burtan** [comment]
I guess I have to wait for a new release version?

**Comment by tangiel** [comment]
Yes, the next version will have it. It should be released today or Monday.
