### ISSUE TITLE
Special characters in Strings

### ISSUE THREAD

**Issue by Burtan** [cloudendpoints/endpoints-java#40]
Hi,
I've now upgrade to V2 and everything is compiling and running. Thank you for resolving the issues I had. I've now came across an issue with special characters in strings. 
I've saved "König" in the datastore correctly but it is now transmitted as "K?nig". In V1 this was working fine. The same happens to É.

**Comment by Burtan** [comment]
Any ideas?

**Comment by tangiel** [comment]
@Burtan what version are you running on? Does it still happen on 2.0.0 (final)? I am trying this on a method that simply echoes a request back and it seems to be fine.

$ curl -H "Content-Type: application/json" -X POST -d '{"message": "König"}' http://localhost:8080/_ah/api/echo/v1/echo
{
 "message": "König"
}

**Comment by Burtan** [comment]
Yes, it happens with 2.0.0. Is your test using a String as the return type? It happens for me using a class containing a String variable. Maybe that matters.

**Comment by tangiel** [comment]
No, raw String isn't allowed as a return type in Endpoints. This is a Message class containing a String field. I will keep looking into it. If you can find a repro that doesn't involve datastore (or just nothing sensitive for you) then I'll be happy to take it. Thanks!

**Comment by Burtan** [comment]
I'll look into it.

**Comment by Burtan** [comment]
This problem has something to do with the openapi-doc file that is submitted to gcloud. I have created a new endpoints class with exactly the same code as the problematic endpoints class and the characters were transmitted correctly. Then I created a new openapi-doc and submitted it to gcloud/updated the entry in the appengine-web.xml file. This lead to the same error as in the original endpoints class.

**Comment by Burtan** [comment]
This is a part of the problematic openapi-doc
```
  "/myApi/v1/chars": {
   "post": {
    "operationId": "MyApiGetRbRef",
    "parameters": [
     {
      "in": "body",
      "name": "body",
      "required": false,
      "schema": {
       "$ref": "#/definitions/RbRefRequest"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "A successful response",
      "schema": {
       "$ref": "#/definitions/RbRefResponse"
      }
     }
    },
    "security": [
     {
      "google_id_token": [ ]
     },
     {
      "google_id_token_https": [ ]
     }
    ],
    "x-security": [
     {
      "google_id_token": {
       "audiences": [
        "XXX.apps.googleusercontent.com"
       ]
      }
     },
     {
      "google_id_token_https": {
       "audiences": [
        "XXX.apps.googleusercontent.com"
       ]
      }
     }
    ]
   }
  }
```

**Comment by tangiel** [comment]
Are the contents of your `web.xml` the same? I wonder if the `GoogleAppEngineControlFilter` is mangling the output somehow.

**Comment by Burtan** [comment]
Yes, I didn't change web.xml

**Comment by tangiel** [comment]
So let me restate it to see if I understand: If you add a new endpoint and use the old OpenAPI document, it works. If you upload a new OpenAPI document that includes the new endpoint, it breaks?

**Comment by Burtan** [comment]
Yes, you got it right.

**Comment by tangiel** [comment]
Thanks. This indicates an issue with the endpoints-management-java repo then, but it helps narrow it down a lot.

**Comment by tangiel** [comment]
This should be fixed if you upgrade your endpoints-management dependency to 1.0.1.

**Comment by patflynn** [comment]
I don't have any explicit endpoints-management dep in my project. Is that a
transitive of endpoints-framework:2?

**Comment by tangiel** [comment]
No, are you seeing issues with just the standard framework?

**Comment by patflynn** [comment]
I think so. I'm seeing this bug when I run an App Engine Standard App using
the endpoints-framework library on the dev appserver.

https://github.com/patflynn/appengine-potpourri/tree/cloud-sdk-refactor
cd endpoints-frontend
mvn appengine:run

**Comment by tangiel** [comment]
Can you paste a sample request?

**Comment by patflynn** [comment]
You mean this:
http://localhost:43386/_ah/api/discovery/v1/apis/potApi/v1/rest?fields=kind%2Cname%2Cversion%2CrootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods&pp=0

**Comment by tangiel** [comment]
Yes, and what is the special character you're not seeing correctly?

**Comment by patflynn** [comment]
I'm not having a special character issue. :)

I think I've somehow got issues mixed up.

This is my issue:
https://github.com/cloudendpoints/endpoints-java/issues/43
