### ISSUE TITLE
Api method paths starting with a slash generating wrong path in discovery file

### ISSUE THREAD

**Issue by clementdenis** [cloudendpoints/endpoints-java#50]
Since beta.10, api method paths starting with a slash are not written correctly to the discovery file.
This makes clients relying on the discovery (API explorer, gapi) return 404s for these methods.
This was a supported feature in legacy Cloud Endpoints.

Here is an example:
- The [Api method](https://gist.github.com/clementdenis/305f593028d60b1295ca5c099fa38fd6#file-specialfeaturesapi-java-L26), annotated with @ApiMethod(path = "/specialFeatures/v1/hello2")
- Discovery generated by beta.9 => the [path is "hello2"](https://gist.github.com/clementdenis/305f593028d60b1295ca5c099fa38fd6#file-discovery-2-0-0-beta-9-json-L105) as expected
- Discovery generated by 2.0.0 final => the [path is "/specialFeatures/v1/hello2"](https://gist.github.com/clementdenis/305f593028d60b1295ca5c099fa38fd6#file-discovery-2-0-0-json-L101), generating paths with a double prefix (/_ah/api/specialFeatures/v1//specialFeatures/v1/hello2)

**Comment by tangiel** [comment]
What is the purpose of re-specifying the /specialFeatures/v1 again? Isn't the intended purpose to specify methods outside of the API-version prefix?

**Comment by clementdenis** [comment]
This was probably the worst possible example :-)
Our APIs have some overridden prefix path, sometimes not including the API version, like this:
@ApiMethod(path = "/pathoverride/hello")

This used to work perfectly with the legacy endpoints. 
With latest v2 builds, these methods are bound to the right path, but the discovery file is wrong.

**Comment by tangiel** [comment]
This is now fixed.
