### ISSUE TITLE
1.9.30 GAE dependency

### ISSUE THREAD

**Issue by ludoch** [cloudendpoints/endpoints-java#51]
Not sure why we need this, but I see 1.9.30 in https://github.com/cloudendpoints/endpoints-java/blob/087db2f1714e9b2204f6c698d91f9145ef24bc90/gradle.properties
and 1.9.30 popups as a dependency on this Maven plugin as well...
Should we either cut the dep or move it to 1.9.49 and keep it up to date every time there is a release of the endpoints artifact?

**Comment by ludoch** [comment]
@loosebazooka FYI, might want to notify Patrick... Endpoints tooling should also not depend on appengine SDK (or why?)

**Comment by loosebazooka** [comment]
I think this is an issue for @tangiel ? Is the dependency necessary?

**Comment by tangiel** [comment]
We're working on making the SDK dependency optional in the core framework (mostly done). Our command line tool actually depends on the App Engine CLI classes, so we can't remove the dependency there yet.

**Comment by ludoch** [comment]
So we can at least use 1.9.49 and have some manual process to verify once
in a while it is up to date.

**Comment by tangiel** [comment]
Yep, I submitted a change to update to 1.9.49.
