### ISSUE TITLE
GetDiscoveryDocAction should validate APIs with ApiConfigValidator

### ISSUE THREAD

**Issue by clementdenis** [cloudendpoints/endpoints-java#61]
Currently, APIs are validated by ApiConfigValidator only on [GenApiConfigAction](https://github.com/cloudendpoints/endpoints-java/blob/master/endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GenApiConfigAction.java#L94) and GetOpenApiDocAction (through [SwaggerGenerator](https://github.com/cloudendpoints/endpoints-java/blob/master/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L157)) tools.
GetDiscoveryDocAction should do it as well.

**Comment by tangiel** [comment]
This will be fixed by #68.
