### ISSUE TITLE
endpoints_get_discovery_doc goal broken since appengine-maven-plugin 1.9.49

### ISSUE THREAD

**Issue by clementdenis** [cloudendpoints/endpoints-java#63]
In appengine-maven-plugin 1.9.49, the dependency to endpoints-framework was updated to 2.0.0.
In this version, the -f (format) parameter was removed from [GetDiscoveryDocAction](https://github.com/AODocs/endpoints-java/commit/09f40f515b6382aa4330ee49040657aeb3895578#diff-598692771343b3511497c4e4b692c3c6L45). 

But the appengine plugin still calls EndpointsTool with the -f parameter when executing the endpoints_get_discovery_do goal, causing this very unclear error:
`Failed to execute goal com.google.appengine:appengine-maven-plugin:1.9.49:endpoints_get_discovery_doc (default) on project aodocs-api: -f`

The appengine-maven-plugin should be updated to remove the -f flag when calling EndpointsTool, or support for this flag should be restored in GetDiscoveryDocAction.

**Comment by tangiel** [comment]
This is being fixed outside of our team. It may already be fixed.
