### ISSUE TITLE
Consider making PropertyParameterNameConflictException a warning instead of a blocking error

### ISSUE THREAD

**Issue by clementdenis** [cloudendpoints/endpoints-java#64]
When using Endpoints v2, our API deployment fails because some API methods have conflicting parameter and field  names (checked in ApiConfigValidator.validateResourceAndFieldNames by throwing PropertyParameterNameConflictException). This makes the whole deployment fail, even if only some methods have the issue.

What is very weird is that we have been deploying these exact same APIs using Endpoints v1 for months now, without any error. The non-conflicting parameter / field name rule used to be enforced as well in Endpoints v1 (we had this issue a few years ago, and [others too](http://stackoverflow.com/questions/32032820/parameter-name-conflicts-with-a-property-in-the-resource)), but the enforcement seems to have been very "random" and probably removed at some point.

Anyway, these API methods with conflicting names work perfectly in Endpoints v1 and in v2 before 2.0.1 ([this commit](https://github.com/cloudendpoints/endpoints-java/commit/a3b885106dc9361bd1fc4cc7f5d4aca856028e4b#diff-145e4646c60b58d2d60b2124a3ed7275R224) reintroduced strict validation), so I don't really understand why this rule even exists. It might be related to the way gapi.client works (it "merges" the API method parameters and the resource fields), but there's an [easy but undocumented workaround](http://stackoverflow.com/questions/19804951/google-cloud-endpoints-making-calls-with-js-client-passing-params-and-json-bo) to make it work (use "resource" field to provide a resource).

Considering that conflicting parameter name are not causing any issue at runtime (until the strict validation was reintroduced in 2.0.1), and that there is an easy solution to use gapi.client with them anyway, this rule should be a warning instead of failing completely at runtime.

**Comment by tangiel** [comment]
Thanks for the report. The intent was to not change the behavior at all, so I'll look into it. This was originally added not because of gapi, but because of a deficiency in the Endpoints protocol, which does the merging that you describe. Therefore, even if it was allowed, you would always only get one value or the other.

**Comment by tangiel** [comment]
This will be fixed by #68.
