### ISSUE TITLE
Delete method endpoint gives 404 error

### ISSUE THREAD

**Issue by Burtan** [cloudendpoints/endpoints-java#67]
Hi,

I'm using an endpoint with a POST PUT and DELETE method. POST and PUT work fine but when calling DELETE it always return an 404 error.

```
@ApiMethod(httpMethod = ApiMethod.HttpMethod.DELETE)
public void removeSong(@Named("songId") String songId, @Named("removeDate") Date removeDate,
                                         User user)
            throws OAuthRequestException, BadRequestException {
}
```

Any ideas?

**Comment by tangiel** [comment]
Are you sure you're hitting the right URL? I notice that you aren't actually specifying it. I believe our legacy URL computation has been a little confusing at times, but it has been left in place (or attempted to). Check your discovery doc to make sure your path is correct.

**Comment by Burtan** [comment]
I can use the api-explorer and the java-client generated by discovery docs, in both cases I get 404. The URL of post/delete requests in the log are the some, while post works.

**Comment by tangiel** [comment]
Can you paste the discovery document fragment for the method in question?

**Comment by Burtan** [comment]
```
 "songs": {
   "methods": {
    "getSong": {
     "httpMethod": "POST",
     "id": "myApi.songs.getSong",
     "path": "songs",
     "request": {
      "$ref": "GetSongRequest",
      "parameterName": "resource"
     },
     "response": {
      "$ref": "GetSongResponse"
     },
     "scopes": [
      "https://www.googleapis.com/auth/userinfo.email"
     ]
    },
    "putSong": {
     "httpMethod": "PUT",
     "id": "myApi.songs.putSong",
     "path": "songs",
     "request": {
      "$ref": "PutSongRequest",
      "parameterName": "resource"
     },
     "response": {
      "$ref": "PutSongResponse"
     },
     "scopes": [
      "https://www.googleapis.com/auth/userinfo.email"
     ]
    },
    "removeSong": {
     "httpMethod": "DELETE",
     "id": "myApi.songs.removeSong",
     "parameterOrder": [
      "songId",
      "removeDate"
     ],
     "parameters": {
      "songId": {
       "location": "path",
       "required": true,
       "type": "string"
      },
      "removeDate": {
       "format": "date-time",
       "location": "path",
       "required": true,
       "type": "string"
      }
     },
     "path": "songs",
     "response": {
      "$ref": "RemoveSongResponse"
     },
     "scopes": [
      "https://www.googleapis.com/auth/userinfo.email"
     ]
    }
   }
  }
 },
```

**Comment by tangiel** [comment]
This looks like a bug/usability issue. Basically, it thinks that songId and removeDate are path parameters. However, they don't actually appear in the path. Can you try adding `@Nullable` after each `@Named` to see if it fixes it?

**Comment by Burtan** [comment]
Yeah, `@Nullable` fixes the problem

**Comment by Burtan** [comment]
This is actually a bigger deal than initially thought. I've got a different app which now gets the 404 error as well with updated dependencies. I've added @Nullable and it is now working again. But I had to change the client code:

Before:
`myApi.service().delete(id).execute();`
After:
`myApi.service().delete().setId(id).execute();`

It's problematic because now old versions throw 404, which makes the changes backward incompatible.

**Comment by Burtan** [comment]
I've narrowed down the problem. I'm using the endpoints-framework-gradle-plugin with endpoints-framework-tools in the classpath:
`classpath 'com.google.endpoints:endpoints-framework-tools:X.X.X'`
Version 2.0.0 works fine with the old version. Version 2.0.1 won't work anymore.

**Comment by tangiel** [comment]
This should get fixed by https://github.com/cloudendpoints/endpoints-java/pull/77.

**Comment by tangiel** [comment]
Closing this issue. Please comment if it's still broken in 2.0.5.
