### ISSUE TITLE
Absolute method paths with different prefixes in same API generates an invalid discovery file

### ISSUE THREAD

**Issue by clementdenis** [cloudendpoints/endpoints-java#74]
If two methods in the same API have no path prefix segments in common (@ApiMethod(path = "/path1/v1") and @ApiMethod(path = "/path2/v1/") for example), the generated discovery file will lack the "servicePath" field. This will make the API explorer call a wrong url:  https://<appid>.appspot.com/_ah/api/_ah/api/<methodpath>.

In this situation, the legacy framework will output an empty servicePath field instead, which is OK with the API explorer.

Full example [here](https://gist.github.com/clementdenis/083bc0eba365e3d295619f3cb8db62e2):
- legacy: [servicePath is present but empty](https://gist.github.com/clementdenis/083bc0eba365e3d295619f3cb8db62e2#file-servicepathmissing-v1-rest-legacy-json-L17)
- framework v2: [no servicePath field](https://gist.github.com/clementdenis/083bc0eba365e3d295619f3cb8db62e2#file-servicepathmissing-v1-rest-frameworkv2-json-L91)

**Comment by tangiel** [comment]
This is fixed by #76
