### ISSUE TITLE
Allow passing in application ID for v1.1 client lib and discovery doc generation

### ISSUE THREAD

**Issue by loosebazooka** [cloudendpoints/endpoints-java#80]
New appengine deployments (with gcloud) do not require (and warn against) inclusion of `<application>` tag in appengine-web.xml.

If the tools could allow this to be passed in via parameter during endpoints-tools action, then the user could customize this at generation time.

see for more : https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin/issues/30

**Comment by patflynn** [comment]
@tangiel any thoughts on this?  We'd like to have a solution before we cut our docs over to the new toolchain.

**Comment by tangiel** [comment]
I was discussing with @loosebazooka that we might just allow a hostname instead of app id since we really just use the app id to compute the hostname anyway. Thoughts?

**Comment by loosebazooka** [comment]
would that mean it would work with custom domains?

**Comment by tangiel** [comment]
As long as the plugin could expose it somehow, yes. Note that the hostname used here is only used as a *default* for generated clients. You can override it in the client pretty easily as well.

**Comment by loosebazooka** [comment]
sure, that works for us

**Comment by tangiel** [comment]
Fix is in #83.

**Comment by tangiel** [comment]
This is submitted and will be in 2.0.6.
