### ISSUE TITLE
Guice - Discovery Docs Not working

### ISSUE THREAD

**Issue by rahultongia** [cloudendpoints/endpoints-java#99]
Hi,

I am using Guice to migrate from v1 to v2 endpoints. However, on doing my ./gradlew clean build, I see that discovery docs are not being generated. It seems like in the class com.google.api.server.spi.tools.WebXml, call by :endpointsDiscoveryDocs the services classes are hardcoded. 

  /**
   * Find endpoint service classes defined in the web.xml.
   *
   * Looks for a servlet with servlet-class = SystemServiceServlet or
   * {@link EndpointsServlet}.
   * Does NOT handle the case of multiple mappings to the same servlet-class,
   * it will only return the result to first one that defines the "services" init-param
   * Does NOT validate that the servlet has a corresponding servlet-mapping
   *
   * @return a list of endpoints service classes
   */
  public List<String> endpointsServiceClasses() {
    XPath xpath = XPathFactory.newInstance().newXPath();
    String findService = "/web-app/servlet" + "["
        + "servlet-class = 'com.google.api.server.spi.SystemServiceServlet'"
        + " or "
        + "servlet-class = '" + EndpointsServlet.class.getName() + "'"
        + "]/init-param[param-name = 'services']/param-value/text()";

    try {
      String servicesString = (String) xpath.evaluate(findService, document, XPathConstants.STRING);
      List<String> services = Lists.newArrayList();
      for (String service : servicesString.trim().split(",")) {
        if (!Strings.isNullOrEmpty(service.trim())) {
          services.add(service.trim());
        }
      }
      return services;
    }
    catch (XPathExpressionException e) {
      throw new RuntimeException(e);
    }
  }

Below are the gradle logs:
Rahuls-MBP:migration-example rahul$ ./gradlew clean build
Starting a Gradle Daemon, 1 busy and 1 incompatible Daemons could not be reused, use --status for details
:clean
:compileJava
:processResources NO-SOURCE
:classes
:endpointsDiscoveryDocs
get-discovery-doc

Generates discovery documents

Usage: <Endpoints tool> get-discovery-doc <options> <service class>...

Options:
  -cp CLASSPATH, --classpath=CLASSPATH
    Lets you specify the service class or classes from a path other than the
    default <war-directory>/WEB-INF/libs and <war-directory>/WEB-INF/classes,
    where <war-directory is the directory specified in the war option, or simply
    ./war if that option is not supplied.
  -o OUTPUT_DIR, --output=OUTPUT_DIR
    Sets the directory where the output will be written to. Default: the
    directory the tool is invoked from.
  -w WAR_PATH, --war=WAR_PATH
    Sets the path to the war directory where web-appengine.xml and other
    metadata are located. Default: ./war.
  -h HOSTNAME, --hostname=HOSTNAME
    Sets the hostname for the generated document. Default is the app's default
    hostname.
  -p BASE_PATH, --path=BASE_PATH
    Sets the base path for the generated document. Default is /_ah/api.

Example:
  <Endpoints tool> get-discovery-doc com.google.devrel.samples.ttt.spi.BoardV1 com.google.devrel.samples.ttt.spi.ScoresV1

:_zipDiscoveryDocs NO-SOURCE
:war
:explodeWar
:assemble
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 9.862 secs

**Comment by rahultongia** [comment]
We can drop this issue. The problem was in my usgae of https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin

**Comment by frankyn** [comment]
@rahultongia could you add what was confusing? Thanks!

**Comment by rahultongia** [comment]
@frankyn The serviceClasses list was to be provided to the server eg.
endpointsServer{
hostname = "${appengineAppName}.appspot.com"
serviceClasses = ['com.famelabs.frontend.api.AdminAPI']
}

I was trying to add those to the endpointsDiscoveryDocs task which, which was always being ignored.
